name: Docker Image CI

on:
  push:
    branches: [ "RELEASE_BRANCH" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (if not done already in a previous step)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build the Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          IMAGE_TAG=$(date +%s)
          docker build -t $DOCKER_USERNAME/my-private-repo:$IMAGE_TAG -f ./Dockerfile .

      - name: Docker Push
        run: docker push $DOCKER_USERNAME/my-private-repo:$IMAGE_TAG
